apiVersion: v1
kind: ReplicationController
metadata:
  name: quotes-v4
  labels:
    app: quotes
    version: "4"
    tier: backend
spec:
  replicas: 2
  selector:
    app: quotes
    version: "4"
  template:
    metadata:
      labels:
        app: quotes
        version: "4"
        tier: backend
    spec:
      containers:
      - name: quotes
#       FOR DEPLOY FROM DOCKERHUB
#        image: quotes:2
        image: magnuslarsson/quotes:4
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1
