apiVersion: v1
kind: Service
metadata:
  name: portal-service
  labels:
    app: portal
    version: "1"
    tier: frontend
spec:
  type: NodePort
  selector:
    app: portal
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
